version: "3.9"

services:
  mongo:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: smarthack
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: smarthack
      MYSQL_DATABASE: smarthack
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  postgres:
    image: postgres:15.0
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: smarthack
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgres

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.0
    depends_on:
      - "postgres"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: smarthack
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: smarthack
    command: ["start-dev", "--import-realm"]
    ports:
      - "8000:8080"
    volumes:
      - ./seeds/keycloak:/opt/keycloak/data/import

volumes:
  mongo-data:
  mysql-data:
  postgres-data:
