export const FLOWS_MICROSERVICE_URL = process.env.FLOWS_MICROSERVICE_URL;
export const FORMS_MICROSERVICE_URL = process.env.FORMS_MICROSERVICE_URL;
export const EXECUTOR_MICROSERVICE_URL = process.env.EXECUTOR_MICROSERVICE_URL;
