name: ci

run-name: Continuous integration

on: [push]

jobs:
  check-front-end:
    name: Check front end
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies using npm
        run: npm ci

      - name: Check the formatting
        run: npm run format:check

      - name: Run the linter
        run: npm run lint
